# Generated by Django 4.2.2 on 2023-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_author_birthday_alter_author_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
